# Dockerfile pour Vite (Frontend)
FROM node:18-alpine

WORKDIR /app

# Copier les fichiers package.json et package-lock.json
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier le reste des fichiers
COPY . .

# Exposer le port utilisé par Vite
EXPOSE 5173

# Commande pour démarrer Vite en mode développement avec --host
CMD ["npm", "run", "dev", "--", "--host"]
