# Utilise l'image officielle de Node.js
FROM node:18

# Crée et se déplace dans le répertoire de travail
WORKDIR /usr/src/app

# Copie le package.json et installe les dépendances
COPY package*.json ./
RUN npm install

# Copie tout le reste du projet
COPY . .

# Compile le projet NestJS
RUN npm run build

# Expose le port de l'application
EXPOSE 3000

# Commande de démarrage
CMD ["npm", "run", "start:prod"]
